language: "python"
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"
install:
    - "pip install --use-mirrors -r ./test_requirements.txt"
    - "./setup.py develop"
script: "./setup.py nosetests --verbosity=2"
